name: Close Pull Request

on:
  pull_request_target:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Close Pull
        run: gh pr close ${{ github.event.number }} --comment "Auto-closing pull request. We do not accept PRs in this repository. Please commit to https://github.com/poweruptime/poweruptime"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
