name: Close Pull Request

on:
  pull_request_target:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Close & Lock Pull Request
        run: |
          gh pr close ${{ github.event.number }} --comment "Auto-closing pull request. We do not accept PRs in this repository. Please submit it to https://github.com/poweruptime/poweruptime"
          gh pr lock ${{ github.event.number }} --reason "resolved"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
